permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: zzh
  email: hzhzh007@gmail.com
  link: 
  weibo: http://weibo.com/u/2247359222
  github: http://github.com/hzhzh007
  music: 
  linkedin: 

# 站点信息
title: 周洲的博客
description: My personal blog
url: 
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-63703942-1
  url: hzhzh007.github.io

# disqus 设置
disqus:
  shortname: hzhzh007

# 主题设置，自动激活某个标签
active: Go

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
